### ISSUE TITLE
After updating your code still not removing parent category

### ISSUE THREAD

**Issue by soundararajanm1990** [tahiriqbalnajam/Magento2-Remove-Parent-Category-from-Child-Category-URL#1]
After updating your code still not removing parent category

**Comment by tahiriqbalnajam** [comment]
Did you try this
"This plugin will not work directly, you have to save again each category. So in admin open category and save it again. We are trying to acheive this in plugin that it run save command to update all categories soon."

**Comment by soundararajanm1990** [comment]
ok thanks
